version: '3.8'
services:
  db:
    image: postgres:latest
    container_name: db
    hostname: postgres
    restart: always
    env_file:
      - .env
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data

  node_app:
    build: .
    depends_on:
      - db
    ports:
      - "3000:3000"
    env_file:
      - .env



volumes:
  pgdata:
