apiVersion: v1
kind: Service
metadata:
  name: tic-tac-toe-service
  labels:
    app: tic-tac-toe-service
spec:
  type: LoadBalancer
  selector:
    app: tic-tac-toe-app
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 3000